@startuml

skinparam linetype ortho
title Диаграмма прецедентов

:User: as User

left to right direction


rectangle Auth {
    User -- [Регистрироваться в системе]
    User -- [Входить в систему]
    User -- [Выходить из системы]
    User -- [Сбрасывать пароль]
}

rectangle UserInfo {
    User -- [Смотреть данные пользователя]
    User -- [Изменять данные пользователя]
}
rectangle MoneyAccountType {
    User -- [Добавлять типы расчетных счетов]
    User -- [Изменять типы расчетных счетов]
    User -- [Смотреть типы расчетных счетов]
    User -- [Скрывать/Архивировать типы расчетных счетов]
}

rectangle MoneyAccount {
    [Добавлять расчетные счета] -- User
    [Изменять расчетные счета] -- User
    [Смотреть расчетные счета] -- User
    [Скрывать/Архивировать расчетные счета] -- User
    [Импортировать транзакции] -- User
    [Настраивать параметры импорта] -- User
    [Экспортировать транзакции] -- User
    [Настраивать параметры экспорта] -- User
}

rectangle MoneyCategory {
    [Добавлять категории трат/доходов] -- User
    [Изменять категории трат/доходов] -- User
    [Смотреть категории трат/доходов] -- User
    [Скрывать/Архивировать категории трат/доходов] -- User
}

rectangle MoneyTransaction {
    User -- [Добавлять переводы/доходы/расходы]
    User -- [Изменять переводы/доходы/расходы]
    User -- [Смотреть переводы/доходы/расходы]
    User -- [Удалять переводы/доходы/расходы]
}

rectangle Statistic {
     User -- [Смотреть статистику по датам]
     User -- [Смотреть статистику по категориям]
}

rectangle FederalTaxServiceIntegration {
    [Подключать интеграцию с ФНС] -- User
    [Передавать данные с чека] -- User
    [Получать данные с чека] -- User
    [Отключать интеграцию с ФНС] -- User
}

rectangle BankIntegration {
    User -- [Подключать интеграцию с банками]
    User -- [Получить транзакции]
    User -- [Отключать интеграцию с банками]
}

rectangle PermissionMoneyAccount {
    [Приглашать пользователей к счету] -- User
    [Отменить приглашение пользователей к счету] -- User
    [Убирать пользователей из своего счета] -- User
    [Смотреть список приглашений] -- User
    [Принимать приглашения] -- User
    [Отклонять приглашения] -- User
    [Настраивать права доступа] -- User
}

rectangle Currency {
    User -- [Баланс в другой валюте]
    User -- [Баланс в другой валюте по времени]
}

@enduml